### ISSUE TITLE
cap-validator.appspot.com Error

### ISSUE THREAD

**Issue by paullin86** [google/cap-library#60]
after updated java 8
every time I try to valid the  atomfeed  or cap URL
will see 
"ERROR | URL retriever"
![image](https://user-images.githubusercontent.com/13958133/36514541-d66dbe88-17af-11e8-9d1b-5e583dad566e.png)

**Comment by bradgoldstein** [comment]
Do you see this for all cap urls, or just those from the cap-validator.appspot.com?

When I upload a local file, the validator tool successfully validates the CAP.

**Comment by bradgoldstein** [comment]
This should now be fixed following https://github.com/google/cap-library/commit/707f0c4e8394eefe58e7f4f1a9b5c3904e61710f.

Please verify and close the issue. Thanks :)

**Comment by paullin86** [comment]
thx. Brad
